### ISSUE TITLE
Create Roadmap

### ISSUE THREAD

**Issue by stephwright** [mozillascience/open-data-training#1]
Take Roadmap from work week in Seattle w/ @zee-moz and enter into [GH repo](./planning/ROADMAP.md)

See also etherpad: https://public.etherpad-mozilla.org/p/OpenDataRoadmap
- [x] Add primers
- [x] Add specific dates / deadlines
- [x] Add testing plans

**Comment by stephwright** [comment]
Preliminary roadmap created.
Need to update w/ specific dates/deadlines.
Include primers
Include plans to test.

**Comment by stephwright** [comment]
Get feedback from @zee-moz re: roadmap

**Comment by stephwright** [comment]
@kaythaney do we have an idea of when we might be doing another WOW? trying to figure out where to enter that in [roadmap](./planning/ROADMAP.md) for testing?

**Comment by kaythaney** [comment]
that's a topic of discussion for April (and for @zee-Moz @acabunoc @auremoser, in terms of mentorship).  let's nail down then.

sent on the move. apologies for typos.

**Comment by stephwright** [comment]
Thanks!  Will put on back burner til then.  I figure this roadmap will be in constant reiteration as we get things done
