### ISSUE TITLE
Should the Open Data Primer address privacy?

### ISSUE THREAD

**Issue by chadsansing** [mozillascience/open-data-training#14]
Excellent IRL examples and unpacking of the open data rationale. I wonder if this

> But data is also collected by governments, who may be interested in the number and location of potholes on a city street, or the geospatial pattern of new cases in an outbreak of the flu. Corporations and businesses collect data, too. 

opens a discussion about the boundaries of what should be shared openly, subjects' privacy choices, and how researchers can avoid sharing seemingly innocuous data that reveals too much about individuals.

**Comment by stephwright** [comment]
Absolutely! Was just talking to Raegan MacDonald about this yesterday.  Where did you find that quote?

**Comment by chadsansing** [comment]
[Second paragraph](https://github.com/mozillascience/open-data-training/blob/master/Materials/Primers/P1_WhyOpenData.md).

**Comment by stephwright** [comment]
We have plans in the 3d primer (Where to share your data - currently being drafted) to touch lightly on ethics / privacy / legal issues.  We will probably also touch on it in the 5th primer on reuse of data.  Other than that we weren't going to go too deeply into it until we reach the next level of primers that goes into disciplinary specifics -- particularly human subjects data in soc sci and health.  Do you think we need to go more deeply into Primer 1?

So many of these topics are intertwined, I'm trying to be careful about not making any one of them too long but also want to make sure topics get covered appropriately.

**Comment by chadsansing** [comment]
Maybe just mention that you'll address privacy issues in later primers? Doesn't have to be a deep dive - just a heads-up and reminder that privacy concerns are at play when we talk open data, retention, and re-use. Make sense?

**Comment by stephwright** [comment]
👍

**Comment by chadsansing** [comment]
Let's close this?

**Comment by stephwright** [comment]
Added sentence at line 96

**Comment by stephwright** [comment]
Done.  Added sentence at line 96 abt privacy.

On Mon, May 2, 2016 at 6:11 AM, Chad Sansing notifications@github.com
wrote:

> Let's close this?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/mozillascience/open-data-training/issues/14#issuecomment-216230582

## 

## Stephanie Wright

Open Data Training Lead, Mozilla Science Lab
Twitter @shefw  | GitHub @stephwright | Skype: stephanie_4504
ORCID: 0000-0003-3829-318X
"The opposite of 'open' isn't 'closed'.  The opposite of 'open' is
'broken'." ~ John Wilbanks
