### ISSUE TITLE
Neuroscience Open Data Workshop

### ISSUE THREAD

**Issue by alexmorley** [mozillascience/open-data-training#23]
As part of our department's Training day in January '17 I have been asked to give a workshop on Data Sharing. I'm going to start working on some extra stuff for this soon as well drawing up an open data plan with other members on the unit. I thought this might be a nice use case to have up on the repo so shall I put up a planning document / folder up here?

**Comment by stephwright** [comment]
Sorry @alexmorley ... been travelling a lot and just now seeing this.
This is fantastic!  I've added you as a collaborator, so yes, please feel free to add a folder / planning document here!

**Comment by alexmorley** [comment]
No worries I've been crazy busy too. I'll add some things here once I get some time to start working on it properly. Hope your well :)

**Comment by stephwright** [comment]
Great!  Also want to call out how appreciative we are that you have been diving in on the Open Data Open Mic, Open Data Curriculum and the Global Sprint!  It's been great!  
We're going to be start digging back into the Open Data Curriculum again in another week.  
All is well here and hope you are well, also!

**Comment by NguoiThuaKe** [comment]
alexmorley closed this issue over 1 year ago
